version: "3"
services:
  # Auth
  auth:
    build: auth/
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - SIGNING_KEY=a001c3a244ac1f9d1cc9a197cc12f9fa
      - HASH_SALT=affd7407a2ebab039d8fef8c6c5bbde6

  # Dashboards
  ui:
    build: ui/
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - AUTH_PORT=8082
      - TASKS_PORT=8082
      - BILLING_PORT=8083
      - ANALYTIC_PORT=8084
