version: "3"
services:
  # Auth
  auth:
    build: auth/
    ports:
      - 8081:8081
    environment:
      - PORT=8081

  # Dashboards
  ui:
    build: ui/
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - AUTH_PORT=8081
      - TASKS_PORT=8082
      - BILLING_PORT=8083
      - ANALYTIC_PORT=8084
