version: "3"
services:
  # Auth
  auth-migrator:
    build:
      context: ./
      dockerfile: ./.deploy/auth-migrator/Dockerfile
    environment:
      - MSSQL_HOST=ws_it_14.cd.local
      - MSSQL_DB=auth
      - MSSQL_USER=sa
      - MSSQL_PWD=Pwd123456!123456
  auth:
    build:
      context: ./
      dockerfile: ./.deploy/auth/Dockerfile
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - SIGNING_KEY=a001c3a244ac1f9d1cc9a197cc12f9fa
      - HASH_SALT=affd7407a2ebab039d8fef8c6c5bbde6
      - MSSQL_HOST=ws_it_14.cd.local
      - MSSQL_DB=auth
      - MSSQL_USER=sa
      - MSSQL_PWD=Pwd123456!123456
      - KAFKA_HOST=ws_it_14.cd.local
      - KAFKA_PORT=9092
#    depends_on:
#      - auth-migrator

  # Dashboards
  ui:
    build: ui/
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - AUTH_PORT=8082
      - TASKS_PORT=8082
      - BILLING_PORT=8083
      - ANALYTIC_PORT=8084
